/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseDto } from '../../models/api-response-dto';
import { SuccessResponseDto } from '../../models/success-response-dto';

export interface InvitationControllerDeclineInviteV1$Params {
  token: string;
}

export function invitationControllerDeclineInviteV1(http: HttpClient, rootUrl: string, params: InvitationControllerDeclineInviteV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDto & {
'data'?: SuccessResponseDto;
}>> {
  const rb = new RequestBuilder(rootUrl, invitationControllerDeclineInviteV1.PATH, 'post');
  if (params) {
    rb.path('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseDto & {
      'data'?: SuccessResponseDto;
      }>;
    })
  );
}

invitationControllerDeclineInviteV1.PATH = '/v1/invitations/{token}/decline';
