/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseDto } from '../../models/api-response-dto';
import { AssignPermissionsDto } from '../../models/assign-permissions-dto';
import { RoleDto } from '../../models/role-dto';

export interface RoleControllerAssignPermissionsV1$Params {
  role_id: string;
      body: AssignPermissionsDto
}

export function roleControllerAssignPermissionsV1(http: HttpClient, rootUrl: string, params: RoleControllerAssignPermissionsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDto & {
'data'?: RoleDto;
}>> {
  const rb = new RequestBuilder(rootUrl, roleControllerAssignPermissionsV1.PATH, 'post');
  if (params) {
    rb.path('role_id', params.role_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseDto & {
      'data'?: RoleDto;
      }>;
    })
  );
}

roleControllerAssignPermissionsV1.PATH = '/v1/roles/{role_id}/permissions';
