/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RoleControllerAssignPermissionsV1$Params {
  role_id: string;
}

export function roleControllerAssignPermissionsV1(http: HttpClient, rootUrl: string, params: RoleControllerAssignPermissionsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, roleControllerAssignPermissionsV1.PATH, 'post');
  if (params) {
    rb.path('role_id', params.role_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

roleControllerAssignPermissionsV1.PATH = '/v1/roles/{role_id}/permissions';
