/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseDto } from '../../models/api-response-dto';
import { CreateRoleDto } from '../../models/create-role-dto';
import { RoleDto } from '../../models/role-dto';

export interface RoleControllerCreateRoleV1$Params {
      body: CreateRoleDto
}

export function roleControllerCreateRoleV1(http: HttpClient, rootUrl: string, params: RoleControllerCreateRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDto & {
'data'?: RoleDto;
}>> {
  const rb = new RequestBuilder(rootUrl, roleControllerCreateRoleV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseDto & {
      'data'?: RoleDto;
      }>;
    })
  );
}

roleControllerCreateRoleV1.PATH = '/v1/roles';
