/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddMemberDto {

  /**
   * Custom permissions/overrides.
   */
  permissions?: {
};

  /**
   * The role ID to assign.
   */
  role_id: string;

  /**
   * The user ID to add.
   */
  user_id: string;
}
