/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignPermissionsDto {

  /**
   * List of permission IDs to assign.
   */
  permission_ids: Array<string>;
}
