/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLogDto {

  /**
   * The action performed.
   */
  action: string;

  /**
   * The email of the user who performed the action.
   */
  actor_email?: string;

  /**
   * The ID of the user who performed the action.
   */
  actor_id?: string;

  /**
   * The timestamp when the action was performed.
   */
  created_at: string;

  /**
   * The unique identifier of the audit log.
   */
  id: string;

  /**
   * The IP address of the user who performed the action.
   */
  ip_address?: string;

  /**
   * Additional metadata related to the action.
   */
  payload?: {
};

  /**
   * The ID of the resource affected.
   */
  resource_id?: string;

  /**
   * The type of resource affected.
   */
  resource_type?: string;

  /**
   * The tenant ID where the action was performed.
   */
  tenant_id?: string;

  /**
   * The user agent of the user who performed the action.
   */
  user_agent?: string;
}
