/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthTokensDto {

  /**
   * The access token for authenticated requests
   */
  accessToken: string;

  /**
   * The refresh token to obtain new access tokens
   */
  refreshToken: string;
}
