/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRoleDto {

  /**
   * The description of the role.
   */
  description?: string;

  /**
   * The name of the role.
   */
  name: string;
}
