/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationDto {

  /**
   * Creation date.
   */
  created_at: string;

  /**
   * The email of the invited user.
   */
  email: string;

  /**
   * Expiration date.
   */
  expires_at?: string;

  /**
   * The unique identifier of the invitation.
   */
  invitation_id: string;

  /**
   * Custom permissions/overrides.
   */
  permissions?: {
};

  /**
   * The role ID assigned in the invitation.
   */
  role_id: string;

  /**
   * The invitation status.
   */
  status: 'PENDING' | 'ACCEPTED' | 'DECLINED' | 'EXPIRED';

  /**
   * The tenant ID the user is invited to.
   */
  tenant_id: string;

  /**
   * The invitation token.
   */
  token: string;
}
