/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PermissionDto {

  /**
   * The action allowed on the resource.
   */
  action: string;

  /**
   * Creation date.
   */
  created_at: string;

  /**
   * The group this permission belongs to.
   */
  group?: string;

  /**
   * A human-readable label for the permission.
   */
  label?: string;

  /**
   * The unique identifier of the permission.
   */
  permission_id: string;

  /**
   * The resource this permission applies to.
   */
  resource: string;
}
