/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductDto {

  /**
   * When the product was created
   */
  created_at: string;

  /**
   * The name of the product
   */
  name: string;

  /**
   * The user ID who created the product
   */
  owner_id: string;

  /**
   * The price of the product
   */
  price: number;

  /**
   * The unique identifier for the product
   */
  product_id: string;

  /**
   * The stock keeping unit identifier
   */
  sku?: string;

  /**
   * The tenant ID this product belongs to
   */
  tenant_id: string;

  /**
   * When the product was last updated
   */
  updated_at: string;
}
