/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendInviteDto {

  /**
   * The email of the invited user.
   */
  email: string;

  /**
   * Expiration duration in hours.
   */
  expiresInHours?: number;

  /**
   * Custom permissions/overrides.
   */
  permissions?: {
};

  /**
   * The role ID to assign.
   */
  role_id: string;
}
