/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantDto {

  /**
   * Registration date.
   */
  created_at: string;

  /**
   * The primary domain associated with the tenant.
   */
  domain?: string;

  /**
   * The name of the tenant.
   */
  name: string;

  /**
   * The current status of the tenant.
   */
  status: 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED';

  /**
   * The unique identifier of the tenant.
   */
  tenant_id: string;
}
