/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileDto {

  /**
   * The user email
   */
  email: string;

  /**
   * Whether the user email is verified
   */
  isVerified: boolean;

  /**
   * The unique session ID
   */
  jti: string;

  /**
   * User permissions
   */
  permissions: Array<string>;

  /**
   * User roles
   */
  roles: Array<string>;

  /**
   * The user ID
   */
  sub: string;

  /**
   * The tenant ID the user is currently operating in
   */
  tenantId: string;
}
