/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {

  /**
   * Creation date.
   */
  created_at: string;

  /**
   * The email address of the user.
   */
  email: string;

  /**
   * Indicates if the user account is active.
   */
  is_active: boolean;

  /**
   * Indicates if the email has been verified.
   */
  is_verified: boolean;

  /**
   * The last login timestamp.
   */
  last_login?: string;

  /**
   * The full name of the user.
   */
  name?: string;

  /**
   * The unique identifier of the user.
   */
  user_id: string;
}
