/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseDto } from '../../models/success-response-dto';

export interface AuthControllerLogoutV1$Params {
}

export function authControllerLogoutV1(http: HttpClient, rootUrl: string, params?: AuthControllerLogoutV1$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerLogoutV1.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseDto>;
    })
  );
}

authControllerLogoutV1.PATH = '/v1/auth/logout';
