/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseDto } from '../../models/api-response-dto';
import { AuthTokensDto } from '../../models/auth-tokens-dto';
import { LoginDto } from '../../models/login-dto';

export interface AuthControllerLoginV1$Params {
      body: LoginDto
}

export function authControllerLoginV1(http: HttpClient, rootUrl: string, params: AuthControllerLoginV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDto & {
'data'?: AuthTokensDto;
}>> {
  const rb = new RequestBuilder(rootUrl, authControllerLoginV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseDto & {
      'data'?: AuthTokensDto;
      }>;
    })
  );
}

authControllerLoginV1.PATH = '/v1/auth/login';
