/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseDto } from '../../models/api-response-dto';
import { UserProfileDto } from '../../models/user-profile-dto';

export interface AuthControllerGetMeV1$Params {
}

export function authControllerGetMeV1(http: HttpClient, rootUrl: string, params?: AuthControllerGetMeV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDto & {
'data'?: UserProfileDto;
}>> {
  const rb = new RequestBuilder(rootUrl, authControllerGetMeV1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseDto & {
      'data'?: UserProfileDto;
      }>;
    })
  );
}

authControllerGetMeV1.PATH = '/v1/auth/me';
